/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "user_storage.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_init_1 (void  *argp, struct svc_req *rqstp)
{
	return (init_1_svc(rqstp));
}

static int *
_register_user_1 (char * *argp, struct svc_req *rqstp)
{
	return (register_user_1_svc(*argp, rqstp));
}

static int *
_unregister_user_1 (char * *argp, struct svc_req *rqstp)
{
	return (unregister_user_1_svc(*argp, rqstp));
}

static int *
_add_user_1 (struct user  *argp, struct svc_req *rqstp)
{
	return (add_user_1_svc(*argp, rqstp));
}

static struct user *
_get_user_1 (char * *argp, struct svc_req *rqstp)
{
	return (get_user_1_svc(*argp, rqstp));
}

static int *
_add_message_1 (struct message  *argp, struct svc_req *rqstp)
{
	return (add_message_1_svc(*argp, rqstp));
}

static int *
_get_total_messages_1 (char * *argp, struct svc_req *rqstp)
{
	return (get_total_messages_1_svc(*argp, rqstp));
}

static struct message *
_get_message_1 (get_message_1_argument *argp, struct svc_req *rqstp)
{
	return (get_message_1_svc(argp->username, argp->msg_id, rqstp));
}

static void
userstorage_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *register_user_1_arg;
		char *unregister_user_1_arg;
		struct user add_user_1_arg;
		char *get_user_1_arg;
		struct message add_message_1_arg;
		char *get_total_messages_1_arg;
		get_message_1_argument get_message_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case init:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _init_1;
		break;

	case register_user:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _register_user_1;
		break;

	case unregister_user:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _unregister_user_1;
		break;

	case add_user:
		_xdr_argument = (xdrproc_t) xdr_user;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _add_user_1;
		break;

	case get_user:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_user;
		local = (char *(*)(char *, struct svc_req *)) _get_user_1;
		break;

	case add_message:
		_xdr_argument = (xdrproc_t) xdr_message;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _add_message_1;
		break;

	case get_total_messages:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _get_total_messages_1;
		break;

	case get_message:
		_xdr_argument = (xdrproc_t) xdr_get_message_1_argument;
		_xdr_result = (xdrproc_t) xdr_message;
		local = (char *(*)(char *, struct svc_req *)) _get_message_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (USERSTORAGE, USERSTORAGEVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, USERSTORAGE, USERSTORAGEVER, userstorage_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (USERSTORAGE, USERSTORAGEVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, USERSTORAGE, USERSTORAGEVER, userstorage_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (USERSTORAGE, USERSTORAGEVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
