/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "user_storage.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_init_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (init_1_svc(result, rqstp));
}

int
_register_user_1 (char  *argp, void *result, struct svc_req *rqstp)
{
	return (register_user_1_svc(*argp, result, rqstp));
}

int
_unregister_user_1 (char  *argp, void *result, struct svc_req *rqstp)
{
	return (unregister_user_1_svc(*argp, result, rqstp));
}

int
_get_user_1 (get_user_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (get_user_1_svc(argp->username, argp->usr, result, rqstp));
}

int
_add_message_1 (struct message  *argp, void *result, struct svc_req *rqstp)
{
	return (add_message_1_svc(*argp, result, rqstp));
}

int
_get_total_messages_1 (char  *argp, void *result, struct svc_req *rqstp)
{
	return (get_total_messages_1_svc(*argp, result, rqstp));
}

int
_get_message_1 (get_message_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (get_message_1_svc(argp->username, argp->msg_id, argp->md5, argp->msg, result, rqstp));
}

static void
userstorage_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char register_user_1_arg;
		char unregister_user_1_arg;
		get_user_1_argument get_user_1_arg;
		struct message add_message_1_arg;
		char get_total_messages_1_arg;
		get_message_1_argument get_message_1_arg;
	} argument;
	union {
		int init_1_res;
		int register_user_1_res;
		int unregister_user_1_res;
		int get_user_1_res;
		int add_message_1_res;
		int get_total_messages_1_res;
		int get_message_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case init:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_init_1;
		break;

	case register_user:
		_xdr_argument = (xdrproc_t) xdr_char;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_register_user_1;
		break;

	case unregister_user:
		_xdr_argument = (xdrproc_t) xdr_char;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_unregister_user_1;
		break;

	case get_user:
		_xdr_argument = (xdrproc_t) xdr_get_user_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_get_user_1;
		break;

	case add_message:
		_xdr_argument = (xdrproc_t) xdr_message;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_add_message_1;
		break;

	case get_total_messages:
		_xdr_argument = (xdrproc_t) xdr_char;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_get_total_messages_1;
		break;

	case get_message:
		_xdr_argument = (xdrproc_t) xdr_get_message_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_get_message_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!userstorage_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (USERSTORAGE, USERSTORAGEVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, USERSTORAGE, USERSTORAGEVER, userstorage_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (USERSTORAGE, USERSTORAGEVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, USERSTORAGE, USERSTORAGEVER, userstorage_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (USERSTORAGE, USERSTORAGEVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
