/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "user_storage.h"

bool_t
xdr_get_user_1_argument (XDR *xdrs, get_user_1_argument *objp)
{
	 if (!xdr_pointer (xdrs, (char **)&objp->username, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->usr, sizeof (struct user), (xdrproc_t) xdr_user))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_message_1_argument (XDR *xdrs, get_message_1_argument *objp)
{
	 if (!xdr_pointer (xdrs, (char **)&objp->username, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->msg_id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->md5, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->msg, sizeof (struct message), (xdrproc_t) xdr_message))
		 return FALSE;
	return TRUE;
}
