/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "queue.h"
#include "dlinkedlist.h"
#include "user_storage.h"


void
userstorage_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  *result_2;
	char *register_user_1_username;
	int  *result_3;
	char *unregister_user_1_username;
	struct user  *result_4;
	char *get_user_1_username;
	int  *result_5;
	struct message add_message_1_msg;
	int  *result_6;
	char *get_total_messages_1_username;
	struct message  *result_7;
	char *get_message_1_username;
	u_int  get_message_1_msg_id;

#ifndef	DEBUG
	clnt = clnt_create (host, USERSTORAGE, USERSTORAGEVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1(clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = register_user_1(register_user_1_username, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = unregister_user_1(unregister_user_1_username, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = get_user_1(get_user_1_username, clnt);
	if (result_4 == (struct user *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = add_message_1(add_message_1_msg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = get_total_messages_1(get_total_messages_1_username, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = get_message_1(get_message_1_username, get_message_1_msg_id, clnt);
	if (result_7 == (struct message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	userstorage_1 (host);
exit (0);
}
